### ISSUE TITLE
Most pages have the same <title>

### ISSUE THREAD

**Issue by moxious** [neo4j-documentation/developer-resources#131]
In `head_partial.erb` the `<title>` HTML tag is hard-coded to be the same title for pretty much every page.

I'm unsure of the ruby templating bits of how to state a title in the asciidoc pages, but that variable needs to be set, and then I guess head_partial.erb needs to substitute it.

Will look further into this when I can get the time.

**Comment by JMHReif** [comment]
The title is actually coming from the neo4j.com project header and not from this file (I know, confusing). I don't believe this head_partial.erb is getting used right now. And I did verify that our developer pages have differing titles. Might still be something we can clean up at some point still!
