### ISSUE TITLE
Fix the Desktop conenction to Aura to use neo4j URI scheme instead of bolt+routing

### ISSUE THREAD

**Issue by pierremartignon** [neo4j-documentation/developer-resources#211]
Since version 1.2.7 the desktop enforce and implemented `neo4j` scheme to connect to Aura instance.
This needs to be reflected in https://neo4j.com/developer/aura-connect-neo4j-desktop/ instructions

**Comment by pierremartignon** [comment]
Tagging @adam-cowley for attention

**Comment by jexp** [comment]
@pierremartignon why did you close the issue?

**Comment by adam-cowley** [comment]
Should this be `neo4j+s://` rather than `neo4j://`?
