### ISSUE TITLE
java server extension not working

### ISSUE THREAD

**Issue by jmozah** [neo4j-documentation/developer-resources#33]
i followed the doc.. but when i do "mvn compile exec:java".. i am getting 

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (default-cli) on project neo4j-movies: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java are missing or invalid -> [Help 1]

i am sure i am missing something silly.. please help..

./Zahoor

**Comment by jmozah** [comment]
I should have put this in mailing list... sorry...

**Comment by kbastani** [comment]
It's OK to add issues here if you feel like something in the guides on `http://www.neo4j.com/developer/get-started` is unclear. No worries.
