### ISSUE TITLE
Running server-extension java example

### ISSUE THREAD

**Issue by teocomi** [neo4j-documentation/developer-resources#35]
Hello all,
I'm trying to run the server-extension java example, I have no experience with java and some help would be extremely appreciated. So far I have:
- forked the repository
- installed eclipse with m2e
- imported language-guides\java\server-extension\pom.xml into eclipse

Now I'm a bit stuck on how to run the code. Since from m2e I cannot do 
    mvn compile exec:java 
I have tried the running the package with the following configuration:
![image](https://cloud.githubusercontent.com/assets/2679513/4889106/197abeee-6393-11e4-9792-c8bc5480bb3f.png)

But an error says that: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java are missing

If in the Run Configuration I add the paramenter "exec.mainClass" with value "example.extension.movies.MovieResource" then I get another error saying that there is no "main" method defined.

Am I missing something? What is the correct Run Configuration?

**Comment by jexp** [comment]
Perhaps if you get started you should rather look into the JDBC example? That should be easier to get started with.

**Comment by jexp** [comment]
I updated the readme with the correct information. Thanks for pointing it out.

**Comment by teocomi** [comment]
Great I get it to compile now, thanks!
