### ISSUE TITLE
Using Neo4j from .NET: Update Content

### ISSUE THREAD

**Issue by whatSocks** [neo4j-documentation/developer-resources#51]
Content is sparse and may be out of date. 

For Neo4jClient, how about summarizing and linking to these instructions?
https://github.com/Readify/Neo4jClient/wiki

Assuming @tathamoddie is ok with this?

Something similar for @mtranter's CypherNet ?

**Comment by jexp** [comment]
I asked @gpierrick to take care of this.

**Comment by gpierrick** [comment]
@jexp I'll try adding more sample projects in the near future too with like different queries
