### ISSUE TITLE
Suggestion: Graph Visualization for Neo4j

### ISSUE THREAD

**Issue by whatSocks** [neo4j-documentation/developer-resources#53]
There are many great resources for data visualization + Neo4j (a lot of D3 stuff). This the current just mentions D3 and moves on to commercial packages. 

How about separating Graph Visualization into different files (similar to how the drivers are organized) and having an article per graph visualization method?

**Comment by jexp** [comment]
Good idea, I'd love t collect content in one file first and then split it out.
We should make sure we have the content from the old visualization page included.
