### ISSUE TITLE
Spring-boot and spring-data-neo4j 3.3.0 Incompatibility

### ISSUE THREAD

**Issue by joshuacano** [neo4j-documentation/developer-resources#69]
So it seems that getting Spring-boot and spring-data-neo4j 3.3.0 to talk to each other proves troublesome. I have tried doing several of the different examples for Spring boot and all work fine until I try and use spring-data-neo4j 3.3.0 or higher. I've been banging my head against this wall for a few days, does anyone have any advice for me on how to implement a simple rest interface using spring-data-neo4j-3.3.0? This is mostly for faster iterative development on eventual server extension methods. The error I continously get is:

java.lang.NoClassDefFoundError: org/springframework/data/mapping/PersistentPropertyAccessor

**Comment by joshuacano** [comment]
Wow. I had an incorrectly mapped repository directory. Completely my mistake, Was not an issue between the two packages.

**Comment by stephaneeybert** [comment]
I wonder what you mean with an incorrectly mapped repository directory. I'm facing the same exception.

**Comment by rnagulapalle** [comment]
what is this issue?

**Comment by joshuacano** [comment]
If I remember correctly, My issue was in my .xml configuration I had incorrectly set the path to the neo4j path in my eclipse project.
